[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "osapiclient"

[project]
name = "osapiclient"
version = "0.1.0"
dependencies = [
  "httpx"
]

